- id: wake_up_alarm_routine
  alias: Wake up alarm routine
  description: play spotify in bedroom and ramp up volume at phone alarm
  trigger:
  - below: '11'
    entity_id: sensor.minutes_next_alarm_antoine
    platform: numeric_state
  action:
  - service: script.turn_on
    target:
      entity_id: script.ramp_up_brightness_ikea_1
    data: {}
  - service: media_player.volume_set
    data:
      volume_level: 0.05
    target:
      entity_id: media_player.linkplay_c5
  - service: script.play_spotify_bedroom
    data:
      start_volume: 0.1
  - service: script.ramp_up_volume
    data:
      media_target: media_player.linkplay_c5
      volume_target: 0.25
      delay: '20000'
  mode: restart
- alias: System - Set Custom Theme at Startup
  id: startup_theme_setup
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: dracula
