#configuration.yaml
# base conf
homeassistant:
  time_zone: "Asia/Tokyo"
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  media_dirs:
    media: /media
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# add themes folder
frontend:
  themes: !include_dir_merge_named themes

# includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# linkplay audiopro
media_player:
  - platform: linkplay
    host: 10.13.89.162
    name: linkplayC5
  - platform: linkplay
    host: 10.13.89.64
    name: LinkplayC10
