services:
  # Home Assistant
  # The core of my smart-home automations
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:2022.8.3
    volumes:
      - ./config/homeassistant:/config
      - ${MEDIA}:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host

  # MQTT
  # A Mosquitto broker for my devices communicating via MQTT
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1888:1883
    volumes:
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # Zigbee2MQTT
  # A bridge for zigbee devices to be able to communicate via MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=${MQTT_SERVER}
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${MQTT_USER}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - /run/udev:/run/udev:ro
      - ./config/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0
    privileged: true
    network_mode: host

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/node-red:/data
    ports:
      - "1880:1880"
    restart: unless-stopped
    depends_on:
      - home-assistant
