# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: auto
jwt_secret: '{{ env "AUTHELIA_JWT_SECRET" }}'

# default_redirection_url: https://blog.antoineglacet.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9092
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug
  format: json
  file_path: "/config/authelia.log"
  keep_stdout: true

totp:
  issuer: antoineglacet.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha2crypt
      sha2crypt:
        variant: sha512
        iterations: 50000
        salt_length: 16

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/18"
  rules:
    - domain: "antoineglacet.com"
      policy: deny
    - domain: "auth.antoineglacet.com"
      policy: bypass
    - domain: "*.antoineglacet.com"
      policy: bypass
      networks:
        - "internal"
    - domain: "*.kanku.dev"
      policy: bypass
      networks:
        - "internal"
    - domain: "*.antoineglacet.com"
      policy: one_factor
      subject:
        - ["group:admins"]
    - domain:
        [
          "home.antoineglacet.com",
          "plex.antoineglacet.com",
          "overseerr.antoineglacet.com",
          "homeassistant.antoineglacet.com",
        ]
      policy: one_factor
      subject:
        - ["group:family"]

    - domain: "handbook.kanku.dev"
      policy: one_factor
      subject:
        - ["group:kap"]

session:
  name: authelia_session
  secret: '{{ env "AUTHELIA_SESSION_SECRET" }}'
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: antoineglacet.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: '{{ env "AUTHELIA_STORAGE_ENCRYPTION_KEY" }}'

notifier:
  disable_startup_check: true #true/false
  smtp:
    username: antoine.glacet@gmail.com #your email address
    password: '{{ env "AUTHELIA_SMTP_PASSWORD" }}'
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: antoine.glacet@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: glacet.antoine@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
