- datetime:
    text_size: md
    format:
        locale: jp
        dateStyle: long
        timeStyle: short
- openmeteo:
    label: Osaka # optional
    latitude: 34.6937
    longitude: 135.5023
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- glances:
    url: https://glances.antoineglacet.com
    disk:
        - /host/media/data

