services:
  # torrent tracker search
  jackett:
    # https://hub.docker.com/r/linuxserver/jackett
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - ./config/jackett:/config
      - ${DOWNLOADS}:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9117:9117
    restart: unless-stopped
  # TV show library
  sonarr:
    # https://hub.docker.com/r/linuxserver/sonarr
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    depends_on:
      - jackett
      - transmission
    restart: unless-stopped
  # movie library
  radaar:
    # https://hub.docker.com/r/linuxserver/radarr
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    hostname: radarr
    volumes:
      - ./config/radarr:/config
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    depends_on:
      - jackett
      - transmission
    restart: unless-stopped
  # plex media server
  plex:
    # https://hub.docker.com/r/linuxserver/plex
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    volumes:
      - ./config/plex:/config
      - ${MEDIA}:/media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - version=docker
    restart: unless-stopped
  # ebooks library manager and server (include webserver)
  calibre:
    # https://hub.docker.com/r/linuxserver/calibre
    # refer to bug described below for version tag
    # https://discourse.linuxserver.io/t/calibre-docker-compose-on-rpi4-no-autostart-gui/4259/3
    image: lscr.io/linuxserver/calibre:arm64v8-arch-version-02a2ceb8
    container_name: calibre
    volumes:
      - ./config/calibre:/config
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8080:8080/tcp # Calibre desktop gui.
      - 8081:8081/tcp # Calibre webserver gui.
    restart: unless-stopped
  # torrent client
  # special image bundled with VPN
  transmission:
    # https://haugene.github.io/docker-transmission-openvpn/
    image: haugene/transmission-openvpn
    container_name: transmission
    volumes:
      - ./config/transmission:/config
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # VPN and networking https://haugene.github.io/docker-transmission-openvpn/provider-specific/
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=${NORDVPN_COUNTRY}
      - NORDVPN_CATEGORY=${NORDVPN_CATEGORY}
      - NORDVPN_PROTOCOL=tcp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - DISABLE_PORT_UPDATER=true
      # Transmission config
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=30
      - TRANSMISSION_WEB_UI=combustion
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "9091:9091"
    restart: unless-stopped
