- id: wake_up_alarm_routine
  alias: Wake up alarm routine
  description: play spotify in bedroom and ramp up volume at phone alarm
  trigger:
  - below: '11'
    entity_id: sensor.minutes_next_alarm_antoine
    platform: numeric_state
  action:
  - service: script.turn_on
    target:
      entity_id: script.ramp_up_brightness_ikea_1
    data: {}
    enabled: false
  - service: media_player.volume_set
    data:
      volume_level: 0.05
    target:
      entity_id: media_player.linkplay_c5
  - service: script.play_spotify_bedroom
    data:
      start_volume: 0.1
  - service: script.ramp_up_volume
    data:
      media_target: media_player.linkplay_c5
      volume_target: 0.25
      delay: '20000'
  mode: restart
- alias: System - Set Custom Theme at Startup
  id: startup_theme_setup
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: dracula
- id: '1693923571591'
  alias: Tag bbc bedroom
  description: ''
  trigger:
  - platform: tag
    tag_id: 4dc623f8-a3e8-4b33-a217-39bb41147e8a
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.linkplay_c5
    data:
      media_content_id: media-source://radio_browser/98adecf7-2683-4408-9be7-02d3f9098eb8
      media_content_type: audio/mpeg
    metadata:
      title: BBC World Service
      thumbnail: http://cdn-profiles.tunein.com/s24948/images/logoq.jpg?t=1
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://radio_browser
      - media_content_type: music
        media_content_id: media-source://radio_browser/popular
  mode: single
- id: tag_test_2_scanned
  alias: Tag Test_2 is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 037cf6da-4893-4925-a90e-9321065f562d
  condition: []
  action:
  - service: script.play_spotify_bedroom
    data: {}
  mode: single
