play_spotify_bedroom:
  alias: play playlist on BedroomC5
  fields:
    start_volume:
      description: volume to start playback
      example: "0.2"
  sequence:
    - service: spotcast.start
      data:
        device_name: "BedroomC5"
        uri: "spotify:playlist:37i9dQZF1DXdQvOLqzNHSW"
        random_song: true
        shuffle: true
  mode: single

ramp_up_volume:
  alias: Ramp up volume
  fields:
    media_target:
      description: The media player to target
      example: media_player.linkplay_c5
    volume_target:
      description: The target volume to increase to
      example: "0.5"
    delay:
      description: The time in ms between volume increment
      example: 1000 (1 second)
  sequence:
    - repeat:
        sequence:
          - delay:
              milliseconds: "{{ delay }}"
          - service: media_player.volume_up
            data:
              entity_id: "{{ media_target }}"
        until:
          - condition: template
            value_template:
              "{{ state_attr(media_target,'volume_level') >= volume_target
              }}"
  mode: single

ramp_up_brightness_ikea_1:
  alias: Ramp up brightness lightbulb_ikea_1
  sequence:
    - alias: "delay 30s"
      delay: 30
    - alias: "turn on bedroom light"
      service: light.turn_on
      target:
        entity_id: light.bedroom_1
      data:
        brightness_pct: 1
    - alias: "ramp up brightness"
      service: light.turn_on
      target:
        entity_id: light.bedroom_1
      data:
        transition: 400
        brightness_pct: 80
  mode: single
