- search:
    provider: duckduckgo
# - datetime:
#     text_size: xl
#     format:
#       timeStyle: short
- openmeteo:
    label: Osaka # optional
    latitude: 50.449684
    longitude: 30.525026
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- resources:
    label: System
    cpu: true
    memory: true
