services:
  # portal to access all other web UI
  heimdall:
    container_name: heimdall
    restart: unless-stopped
    image: linuxserver/heimdall:latest
    volumes:
      - ./config/heimdall:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8002:80
  # fast, modern VPN server
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PEERS=KapPC,Phone #optional
      - PEERDNS=adguard # config with adguard needs work.
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  # share files with Windows
  samba:
    container_name: samba
    image: dperson/samba
    volumes:
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    command: >
      samba.sh
        -w "WORKGROUP"
        -s "data;/data;yes;no;no;all"
        -u "${SAMBA_USER};${SAMBA_PASSWORD}"
        -p
        -n
    restart: unless-stopped
  # Ad-blocking DNS server
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    volumes:
      - ./config/adguard/work:/opt/adguardhome/work
      - ./config/adguard/conf:/opt/adguardhome/conf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 853:853/tcp
      - 8380:80/tcp
      - 8300:3000/tcp
    restart: unless-stopped

  # monitoring with glances  
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    volumes:
      - ./config/glances/glances.conf:/glances/conf/glances.con
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - 61208-61209:61208-61209
    restart: unless-stopped

  # code-server for webUI
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - /workspace=/mnt/home-server # important to have ha extension working
    volumes:
      - ./config/code-server:/config
      - ${HOME_ASSISTANT_IMAGE_CONF}:/mnt/home-server
    ports:
      - 8443:8443
    restart: unless-stopped

  # Contaiers management UI
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer:/data
    ports:
      - 8000:8000 # Agent
      - 9443:9443 # Web UI  
    restart: unless-stopped
